
const state={active:'OVERVIEW',query:'',filter:'ALL',selected:null,data:null};
const navItems=['OVERVIEW','CHARACTERS','ABILITIES','FACTIONS','ORGANIZATIONS','CITY','CHRONICLE','RELATIONSHIPS','DATABASE','ARCHIVE'];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const displayName=c=>c.identity.activity_name||c.identity.real_name||'UNKNOWN';
const faction=c=>c.classification.faction||'무소속';
const tone=c=>{const f=faction(c).toLowerCase(); if(f.includes('villain'))return'villain'; if(f.includes('hero'))return'hero'; return'gray'};
const rank=c=>c.classification.rank||'N/A';
const allChars=()=>state.data.characters.characters;
const findChar=id=>allChars().find(c=>c.id===id);
const textJoin=c=>[displayName(c),c.identity.real_name||'',faction(c),c.ability.name||'',c.ability.description||'',c.classification.ability_class||'',...(c.profile.personality||[]),c.source_text||''].join(' ').toLowerCase();
function setActive(a){state.active=a;state.selected=null;window.scrollTo({top:0,behavior:'smooth'});render();}
function renderNav(){const nav=$('#nav'); nav.innerHTML=navItems.map(n=>`<button class="nav-btn ${state.active===n?'active':''}" data-nav="${n}">${n}</button>`).join('');}
function counts(){const cs=allChars(); const byRank=r=>cs.filter(c=>rank(c)===r).length; return {total:cs.length,main:cs.filter(c=>c.character_type==='main').length,support:cs.filter(c=>c.character_type==='supporting').length,hero:cs.filter(c=>faction(c).toLowerCase().includes('hero')).length,villain:cs.filter(c=>faction(c).toLowerCase().includes('villain')).length,gray:cs.filter(c=>c.classification.faction_modifiers.some(x=>x.includes('그레이존'))||faction(c)==='무소속').length,S:byRank('S'),A:byRank('A'),B:byRank('B'),C:byRank('C'),D:byRank('D')};}
function bar(label,val,max){return `<div class="bar"><div class="bar-top"><span>${esc(label)}</span><b>${val}</b></div><div class="track"><i style="width:${max?Math.round(val/max*100):0}%"></i></div></div>`;}
function portrait(c,detail=false){return `<div class="portrait ${tone(c)} ${detail?'detail-portrait':''}"><div class="grid"></div><span class="badge">#${String(c.source_index).padStart(2,'0')} / ${esc(c.character_type==='main'?'MAIN':'SUPPORTING')}</span><span class="rank">${esc(rank(c))}</span><div class="initial">${esc(displayName(c)[0]||'?')}</div><span class="status">${esc(c.status.life_status||c.status.registration_status||'ACTIVE')}</span></div>`;}
function characterCard(c){return `<button class="card" data-char="${c.id}">${portrait(c)}<div class="card-body"><div class="card-meta"><span>${esc(faction(c))}</span><span>${esc(c.classification.ability_class||'UNCLASSIFIED')}</span></div><h3>${esc(displayName(c))}</h3><p>${esc(c.identity.real_name||'본명 미기재')}</p><div class="tags">${(c.profile.personality||[]).slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div></button>`;}
function overview(){const s=counts();return `<section class="hero"><div><div class="eyebrow">ARCHIVE NODE // BC-001</div><h1>BIKINI<br><em>CITY</em></h1><p class="desc">힘을 가진 사람과, 그 힘을 분류하고 관리하고 이용하는 도시. 비키니시티의 Canon 기록을 탐색 가능한 하나의 아카이브로 집약했습니다.</p><div class="hero-actions"><button class="primary" data-nav="CHARACTERS">ENTER ARCHIVE <span>→</span></button><button class="ghost" data-nav="DATABASE">SYSTEM INDEX</button></div></div><div class="hero-visual"><div class="hero-grid"></div><div class="orbit a"></div><div class="orbit b"></div><div class="core"><small>WORLD</small><strong>ARCHIVE</strong><span>${s.total} RECORDS</span></div><div class="node n1">AWAKENING</div><div class="node n2">HERO / VILLAIN</div><div class="node n3">ABILITY SYSTEM</div><div class="node n4">CITY / ERA</div></div></section>
<section class="metrics">${[['CHARACTERS',s.total,`${s.main} MAIN · ${s.support} SUPPORTING`],['HERO',s.hero,'REGISTERED / ACTIVE'],['VILLAIN',s.villain,'ARCHIVE INDEX'],['CURRENT ERA','III','소강기']].map(x=>`<div class="metric"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('')}</section>
<section class="page"><div class="grid"><article class="panel span-8"><div class="panel-head"><span>WORLD STRUCTURE</span><b>01</b></div><div class="flow">${[['AWAKENING','힘의 발생'],['CLASSIFICATION','4대 이능력 분류'],['RANK','S / A / B / C / D'],['FACTION','HERO / VILLAIN']].map((x,i)=>`<div class="flow-node"><strong>${x[0]}</strong><small>${x[1]}</small></div>${i<3?'<i>→</i>':''}`).join('')}</div></article>
<article class="panel span-4"><div class="panel-head"><span>FACTION INDEX</span><b>02</b></div>${bar('HERO',s.hero,s.total)}${bar('VILLAIN',s.villain,s.total)}${bar('GRAY / OTHER',s.gray,s.total)}</article>
<article class="panel span-6"><div class="panel-head"><span>RANK DISTRIBUTION</span><b>03</b></div>${['S','A','B','C','D'].map(r=>bar(r,s[r],Math.max(s.S,s.A,s.B,s.C,s.D,1))).join('')}</article>
<article class="panel span-6"><div class="panel-head"><span>CITY GRID</span><b>04</b></div><div class="city-mini">${state.data.locations.locations.map(l=>`<button class="city-cell" data-location="${l.id}"><small>ZONE ${String(l.district_number).padStart(2,'0')}</small><strong>${esc(l.name)}</strong><span>${esc(l.alias||l.status.toUpperCase())}</span></button>`).join('')}</div></article>
<article class="panel span-12"><div class="panel-head"><span>CHRONICLE / THREE AGES</span><b>05</b></div><div class="timeline">${state.data.eras.eras.map((e,i)=>`<div class="era ${i===2?'current':''}"><small>AGE ${i+1}</small><h3>${esc(e.name)}</h3><p>${esc(e.subtitle)}</p></div>`).join('')}</div></article></div></section>`;}
function characterIndex(){let cs=allChars();const q=state.query.trim().toLowerCase(); if(q)cs=cs.filter(c=>textJoin(c).includes(q)); const f=state.filter; if(f==='HERO')cs=cs.filter(c=>faction(c).toLowerCase().includes('hero')); else if(f==='VILLAIN')cs=cs.filter(c=>faction(c).toLowerCase().includes('villain')); else if(f==='GRAY')cs=cs.filter(c=>c.classification.faction_modifiers.some(x=>x.includes('그레이존'))||faction(c)==='무소속'); else if(['S','A','B','C','D'].includes(f))cs=cs.filter(c=>rank(c)===f); return `<section class="page"><div class="heading-row"><div><div class="eyebrow">DATABASE / CHARACTER INDEX</div><h2 class="page-title">CHARACTERS</h2></div><div class="count">${cs.length} / ${allChars().length}</div></div><div class="toolbar">${['ALL','HERO','VILLAIN','GRAY','S','A','B','C','D'].map(x=>`<button class="chip ${state.filter===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><div class="search"><span>⌕</span><input id="charSearch" value="${esc(state.query)}" placeholder="인물명, 본명, 진영, 능력, 성격, 원문 검색"></div><div class="cards">${cs.map(characterCard).join('')}</div></section>`;}
function characterDetail(c){const rels=c.relationships||[]; return `<section class="page"><button class="back-link chip" data-nav="CHARACTERS">← RETURN TO INDEX</button><div class="detail-head">${portrait(c,true)}<div class="detail-copy"><div class="eyebrow">${esc(faction(c))} ${rank(c)!=='N/A'?'· '+esc(rank(c))+' RANK':''}</div><h2>${esc(displayName(c))}</h2><div class="real">${esc(c.identity.real_name||'본명 미기재')}</div><div class="detail-stats">${[['HEIGHT',c.profile.height_cm?c.profile.height_cm+'cm':'—'],['MBTI',c.profile.mbti||'—'],['ENNEAGRAM',c.profile.enneagram||'—'],['ABILITY CLASS',c.classification.ability_class||'—']].map(x=>`<span class="stat">${esc(x[0])} · ${esc(x[1])}</span>`).join('')}</div><div class="tags">${(c.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div></div>
<div class="detail-grid"><article class="panel"><div class="panel-head"><span>ABILITY</span><b>01</b></div><h3>${esc(c.ability.name||'미등록')}</h3><p class="page-lead">${esc(c.ability.description||'원문에 별도의 능력 설명이 기록되지 않았습니다.')}</p>${c.ability.limitations?.length?`<div class="sub-block"><small>LIMITATIONS</small><ul>${c.ability.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}</article>
<article class="panel"><div class="panel-head"><span>PROFILE</span><b>02</b></div><table class="table"><tbody>${[['FACTION',faction(c)],['RANK',rank(c)],['ABILITY',c.classification.ability_class||'—'],['HEIGHT',c.profile.height_cm?c.profile.height_cm+'cm':'—'],['MBTI',c.profile.mbti||'—'],['ENNEAGRAM',c.profile.enneagram||'—'],['STATUS',c.status.life_status||c.status.registration_status||'—']].map(x=>`<tr><th>${esc(x[0])}</th><td>${esc(x[1])}</td></tr>`).join('')}</tbody></table><div class="tags">${(c.profile.personality||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></article>
<article class="panel span-12"><div class="panel-head"><span>SPECIAL NOTES / BACKSTORY</span><b>03</b></div>${(c.narrative.special_notes||[]).map(x=>`<p class="page-lead">${esc(x)}</p>`).join('')}<div class="reading">${esc(c.narrative.backstory||'원문에 별도의 백스토리가 기록되지 않았습니다.')}</div></article>
<article class="panel span-6"><div class="panel-head"><span>QUOTES</span><b>04</b></div><div class="quote-block"><small>NORMAL</small><p>${esc(c.quotes.normal?.join(' / ')||'—')}</p></div><div class="quote-block danger"><small>CRISIS</small><p>${esc(c.quotes.crisis?.join(' / ')||'—')}</p></div></article>
<article class="panel span-6"><div class="panel-head"><span>RELATIONSHIP RECORDS</span><b>05</b></div>${rels.length?rels.map(r=>`<div class="rel-card" data-speaker="${r.speaker_id||''}"><small>COMMENT · ${esc(r.speaker_name)}</small><strong>${esc(r.speaker_name)}</strong><p>${esc(r.quote)}</p><em>↗</em></div>`).join(''):'<p class="page-lead">연결된 관련 기록이 없습니다.</p>'}</article></div></section>`;}
function abilities(){const items=state.data.abilities.abilities;return `<section class="page"><div class="eyebrow">SYSTEM / ABILITY INDEX</div><h2 class="page-title">ABILITIES</h2><p class="page-lead">원문에 등장하는 각 캐릭터의 이능력을 독립 레코드로 연결했습니다. 이름이 명시되지 않은 경우 원문 설명을 그대로 보존합니다.</p><div class="section-grid">${state.data['ability-classes'].classes.map(cl=>{const xs=items.filter(a=>a.classification===cl.name);return `<article class="section-card"><small>${esc(cl.id)}</small><h3>${esc(cl.name)}</h3><p>${esc(cl.description)}</p><p style="margin-top:14px">${xs.length} RECORDS</p>${xs.slice(0,5).map(a=>`<div class="rel-card" data-char="${a.user_ids[0]}"><strong>${esc(a.name||'UNNAMED ABILITY')}</strong><p>${esc(findChar(a.user_ids[0])?displayName(findChar(a.user_ids[0])):'')}</p></div>`).join('')}</article>`}).join('')}</div></section>`;}
function factions(){return `<section class="page"><div class="eyebrow">WORLD / FACTION INDEX</div><h2 class="page-title">FACTIONS</h2><div class="section-grid">${state.data.factions.factions.map(f=>{const xs=allChars().filter(c=>faction(c)===f.name);return `<article class="section-card"><small>${f.official?'OFFICIAL':'UNOFFICIAL'}</small><h3>${esc(f.name)}</h3><p>${esc(f.description)}</p><p style="margin-top:14px">${xs.length} CHARACTER RECORDS</p>${xs.slice(0,8).map(c=>`<div class="rel-card" data-char="${c.id}"><strong>${esc(displayName(c))}</strong><p>${esc(rank(c))}</p></div>`).join('')}</article>`}).join('')}</div></section>`;}
function organizations(){return `<section class="page"><div class="eyebrow">CIVIC / ASSOCIATION INDEX</div><h2 class="page-title">ORGANIZATIONS</h2><div class="section-grid">${state.data.organizations.organizations.map(o=>`<article class="section-card"><small>${esc(o.category)}</small><h3>${esc(o.name)}</h3><p>${esc(o.description)}</p><p style="margin-top:14px;color:#69727f">LOCATION · ${esc(o.location_id||o.headquarters_location_id||'—')}</p></article>`).join('')}</div></section>`;}
function city(){return `<section class="page"><div class="eyebrow">SPACE / DISTRICT ARCHIVE</div><h2 class="page-title">BIKINI CITY</h2><p class="page-lead">비키니시티의 1~8구역을 원문에 기재된 지역 성격과 연결 정보 중심으로 탐색합니다.</p><div class="map-grid">${state.data.locations.locations.map(l=>`<button class="zone ${l.status==='restricted'?'restricted':''}" data-location="${l.id}"><b>ZONE ${String(l.district_number).padStart(2,'0')}</b><h3>${esc(l.name)}</h3><p>${esc(l.alias||'')}</p><p>${esc(l.description).slice(0,180)}…</p></button>`).join('')}</div></section>`;}
function chronicle(){return `<section class="page"><div class="eyebrow">HISTORY / CHRONICLE</div><h2 class="page-title">THREE AGES</h2><div class="section-grid">${state.data.eras.eras.map((e,i)=>`<article class="section-card"><small>AGE ${i+1}</small><h3>${esc(e.name)}</h3><p>${esc(e.subtitle)}</p><div class="reading" style="margin-top:18px">${esc(e.description)}</div>${e.event_ids.map(id=>{const ev=state.data.events.events.find(x=>x.id===id);return ev?`<div class="rel-card"><small>EVENT</small><strong>${esc(ev.name)}</strong><p>${esc(ev.description)}</p></div>`:''}).join('')}</article>`).join('')}</div></section>`;}
function relations(){const rs=state.data.relationships.relationships;return `<section class="page"><div class="eyebrow">GRAPH / RELATIONSHIP ARCHIVE</div><h2 class="page-title">RELATIONSHIPS</h2><p class="page-lead">관련캐릭터 발언을 중심으로 원문에서 확인되는 연결을 보존합니다. 직접적인 관계가 명시되지 않은 경우 COMMENT로만 기록했습니다.</p><div class="network"><div class="network-core"><small>WORLD</small><strong>42</strong><small>RECORDS</small></div>${[['a','HERO'],['b','VILLAIN'],['c','ABILITY'],['d','CITY']].map(x=>`<div class="network-node ${x[0]}">${x[1]}</div>`).join('')}</div><table class="table"><thead><tr><th>SOURCE</th><th>TYPE</th><th>TARGET</th><th>RECORD</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${esc(r.source_name)}</td><td>${esc(r.relationship_type)}</td><td>${esc(r.target_name)}</td><td>${esc(r.quote||'—')}</td></tr>`).join('')}</tbody></table></section>`;}
function database(){const s=counts();return `<section class="page"><div class="eyebrow">SYSTEM / RULES</div><h2 class="page-title">DATABASE</h2><div class="grid"><article class="panel span-6"><div class="panel-head"><span>RANK SYSTEM</span><b>S → D</b></div>${state.data.ranks.ranks.map(r=>`<div class="rel-card"><strong>${esc(r.label)}</strong><p>${esc(r.description)}</p></div>`).join('')}</article><article class="panel span-6"><div class="panel-head"><span>ABILITY CLASSIFICATION</span><b>4 TYPES</b></div>${state.data['ability-classes'].classes.map(c=>`<div class="rel-card"><strong>${esc(c.name)}</strong><p>${esc(c.description)}</p></div>`).join('')}</article><article class="panel span-12"><div class="panel-head"><span>TERMS</span><b>${state.data.terms.terms.length}</b></div>${state.data.terms.terms.map(t=>`<div class="rel-card"><small>${esc(t.category)} ${t.official?'· OFFICIAL':'· UNOFFICIAL'}</small><strong>${esc(t.name)}</strong><p>${esc(t.definition)}</p></div>`).join('')}</article></div></section>`;}
function archive(){return `<section class="page"><div class="eyebrow">SOURCE / PROVENANCE</div><h2 class="page-title">ARCHIVE</h2><p class="page-lead">이 프로젝트의 데이터는 「비키니 시티 1차(1).docx」 원문을 기준으로 추출되었습니다. 장문 백스토리·특이사항·대사·관련 발언은 JSON 내부 source_text와 개별 필드에 보존되어 있습니다.</p><div class="section-grid">${[['CHARACTERS',state.data.characters.characters.length],['ABILITIES',state.data.abilities.abilities.length],['ORGANIZATIONS',state.data.organizations.organizations.length],['LOCATIONS',state.data.locations.locations.length],['ERAS',state.data.eras.eras.length],['EVENTS',state.data.events.events.length],['RELATIONSHIPS',state.data.relationships.relationships.length],['TERMS',state.data.terms.terms.length]].map(x=>`<article class="section-card"><small>CANON DATASET</small><h3>${x[0]}</h3><p>${x[1]} RECORDS</p></article>`).join('')}</div></section>`;}
function current(){if(state.selected){const c=findChar(state.selected);if(c)return characterDetail(c)}switch(state.active){case'CHARACTERS':return characterIndex();case'ABILITIES':return abilities();case'FACTIONS':return factions();case'ORGANIZATIONS':return organizations();case'CITY':return city();case'CHRONICLE':return chronicle();case'RELATIONSHIPS':return relations();case'DATABASE':return database();case'ARCHIVE':return archive();default:return overview();}}
function render(){renderNav();$('#content').innerHTML=current();$('#footerStatus').textContent=`${allChars().length} CHARACTERS · CANON SOURCE`;bind();}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>setActive(b.dataset.nav));document.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.char;window.scrollTo({top:0,behavior:'smooth'});render();});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render();});document.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>openLocation(b.dataset.location));document.querySelectorAll('[data-speaker]').forEach(b=>b.onclick=()=>{if(b.dataset.speaker){state.selected=b.dataset.speaker;render();}});const input=$('#charSearch');if(input){input.oninput=e=>{state.query=e.target.value;const pos=e.target.selectionStart;render();const n=$('#charSearch');if(n){n.focus();n.setSelectionRange(pos,pos)}}}}
function openLocation(id){const l=state.data.locations.locations.find(x=>x.id===id);if(!l)return;const chars=l.character_ids.map(findChar).filter(Boolean);$('#modalBody').innerHTML=`<div class="modal-meta">ZONE ${String(l.district_number).padStart(2,'0')} · ${esc(l.status)}</div><h3>${esc(l.name)}${l.alias?' / '+esc(l.alias):''}</h3><p>${esc(l.description)}</p>${l.anomalies.length?`<p><b>ANOMALY</b> · ${esc(l.anomalies.join(', '))}</p>`:''}<div class="tags">${chars.map(c=>`<button class="tag" data-char="${c.id}">${esc(displayName(c))}</button>`).join('')}</div>`;$('#modal').classList.remove('hidden');document.querySelectorAll('#modalBody [data-char]').forEach(b=>b.onclick=()=>{closeModal();state.selected=b.dataset.char;render();});}
function closeModal(){$('#modal').classList.add('hidden');}
async function load(){const files=['characters','abilities','ability-classes','ranks','factions','organizations','locations','eras','events','relationships','terms','artifacts'];const out={};for(const f of files){out[f]=await fetch(`public/data/${f}.json`).then(r=>r.json())}state.data=out;render();}
$('#globalSearchBtn').onclick=()=>{setActive('CHARACTERS');setTimeout(()=>$('#charSearch')?.focus(),50)};
$('#menuBtn').onclick=()=>{const nav=$('#nav');nav.style.display=nav.style.display==='flex'?'':'flex';nav.style.flexDirection='column';nav.style.position='absolute';nav.style.left='0';nav.style.right='0';nav.style.top='78px';nav.style.background='var(--bg)';nav.style.padding='10px 18px';};
$('#modalClose').onclick=closeModal;$('.modal-backdrop').onclick=closeModal;window.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#globalSearchBtn').click()}if(e.key==='Escape')closeModal()});
load().catch(err=>{$('#content').innerHTML=`<section class="page"><h2 class="page-title">ARCHIVE ERROR</h2><p class="page-lead">${esc(err.message)}</p></section>`});
